base: &base
  train_years: [2020,2021,2022]
  valid_years: [2023]
  era5_channel_input: ['u10', 'v10', 't2m', 'sst', 'skt',   'lsm', 'z_1000', 'z_600', 'z_200', 'clwc_800', 'clwc_600', 'clwc_400', 'ciwc_800', 'ciwc_600', 'ciwc_400', 'q_1000', 'q_800', 'q_600', 't_800', 't_600', 't_400',  'u_800', 'u_600', 'u_400', 'v_800', 'v_600', 'v_400']
  era5_channel_output: ['avg_tprate']
  region: 'us_midwest'
  dt: 6 # time interval in hours
  local_batch_size: 1
  distributed: !!bool False
  shuffle: !!bool False
  batch_size: 1
  num_data_workers: 0 #8
  is_subset: !!bool False
  step_start: -1
  step_end: -1

subset_test: &subset_test
  <<: *base
  train_years: [2020]
  valid_years: [2023]
  # Test subset functionality with a small sample
  is_subset: !!bool True
  step_start: 100    # Start at index 100
  step_end: 120      # Use 20 samples for testing
  local_batch_size: 2
  num_data_workers: 0
  era5_channel_input: ['u10', 'v10', 't2m']  # Use fewer channels for faster testing
  era5_channel_output: ['avg_tprate']